---

shadowsocks_local_address: 127.0.0.1
shadowsocks_local_port: 1080
privoxy_listen_port: 8118

###############################
# defaults file for docker
###############################

docker_users:
  - root
  - vagrant
  #  - "{{ ansible_user }}"

# Use podman and buildah instead, or look at Docker-EE
force_docker_on_rhel_8: false

######################################
# defaults file for virtualbox
######################################

# Add users to 'vboxusers' group
setup_users: yes

# List of users to add to 'vboxusers' group
vbox_users:
  - vagrant

# VirtualBox major version to install
virtualbox_version: "6.0"

# Full version number
virtualbox_version_full: "6.0.12"

# Install extensions listed in virtualbox_extpacks_urls (requires license)
install_extpacks: no

# List of VirtualBox extensions to install
virtualbox_extpack_urls:
  - "https://download.virtualbox.org/virtualbox/{{ virtualbox_version_full }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version_full }}.vbox-extpack"


