---
# tasks file for privoxy

- name: Install privoxy
  apt:
    pkg:
    - privoxy
    - python-netaddr
    - python3-netaddr

- name: Upload privoxy config 
  template:
    src: privoxy_config.j2
    dest: /etc/privoxy/config
  notify: privoxy restarted

- name: enable and start privoxy
  systemd:
    name: privoxy
    enabled: yes
    state: started
