---
# tasks file for mpv

- name: Add Mpv media player (FFmpeg version) PPA
  apt_repository:
    repo: ppa:mc3man/mpv-tests

- name: Update repositories cache and install mpv
  apt:
    name: mpv
    update_cache: yes
