---

- name: setup a deployment environment
  hosts: default
  gather_facts: yes
  roles:
    # - role: anaconda
    - role: vscode

- name: setup a virtualization environment
  hosts: default
  gather_facts: yes
  roles:
    - role: vagrant
