---

- name: Setup to beautify the desktop
  hosts: default
  gather_facts: yes
  roles:
    - role: flat-remix

- name: Deployment environment
  hosts: default
  gather_facts: yes
  roles:
    - role: anaconda
    - role: vscode
    # - role: vim
    # - role: jenkins

- name: Virtualization environment
  hosts: default
  gather_facts: yes
  roles:
      - role: vagrant
      - role: virtualbox

- name: Internet application
  hosts: default
  connection: local
  gather_facts: yes
  roles:
    - role: mpv
    - role: syncthing
    - role: firefox
    - role: google-chrome
    - role: aria2-webui

- name: Office application
  hosts: default
  connection: local
  gather_facts: yes
  roles:
    - role: libreoffice
    - role: typora
