---
# tasks file for vscode

- name: Add microsoft gpg key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /usr/share/keyrings/packages.microsoft.gpg
    state: present

- name: Add Ubuntu microsoft repo
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode

- name: Install code
  apt:
    name: code
    update_cache: yes

- name: install extension
  shell: "code --install-extension {{ item }}"
  become: no
  register: result
  when: 
    - vscode_extension is defined
  loop: "{{ vscode_extension }}"
  changed_when: result.stdout is not search('is already installed.')
  ignore_errors: yes
  environment:
    http_proxy: "http://localhost:{{ privoxy_listen_port  }}"
    https_proxy: "http://localhost:{{ privoxy_listen_port  }}"
