---

- name: Install Dnsmasq
  apt:
    pkg:
    - dnsmasq

- name: Disable and stop systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: no
    state: stopped

- name: Check resolv.conf is link
  stat:
    path: /etc/resolv.conf
  register: systemd_resolvd_link

- name: Delete if resolv.conf is link 
  file:
    path: /etc/resolv.conf
    state: absent
  when: systemd_resolvd_link.stat.exists
  notify: NetworkManager restarted

- name: NetworkManager configuration use dnsmasq
  ini_file:
    path: "{{ networkmanager_configuration_directory }}/NetworkManager.conf"
    section: main
    option: dns
    value: dnsmasq
  notify: NetworkManager restarted

- name: Upload dnsmasq template
  template:
    src: "{{ item.src }}"
    dest: "{{ dnsmasq_configuration_directory }}/{{ item.dest }}"
  with_items: "{{ dnsmasq_configuration_files }}"

- name: Insert line in dnsmasq domain config
  lineinfile:
    path: "{{ dnsmasq_configuration_directory }}/domain.conf"
    line: "address=/{{ aria2_webui_domain_name }}/{{ aria2_webui_listen_address }}"
  notify: NetworkManager restarted

- name: Insert line in dnsmasq domain config
  lineinfile:
    path: "{{ dnsmasq_configuration_directory }}/upstream.conf"
    line: "server={{ item }}"
  with_items: "{{ dnsmasq_upstream_dns_servers }}"
  notify: NetworkManager restarted
